name: LeetTranslator
version: 0.2.0
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: ">=0.13.0 <0.14.0"
  quiver: '>=0.21.0 <0.22.0'
dev_dependencies:
  unittest: any
